[2024-07-03T21:07:22.295+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-03T21:07:22.866+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exchange_rate_dag.run_script scheduled__2023-07-23T00:00:00+00:00 [queued]>
[2024-07-03T21:07:23.054+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exchange_rate_dag.run_script scheduled__2023-07-23T00:00:00+00:00 [queued]>
[2024-07-03T21:07:23.078+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-03T21:07:23.443+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): run_script> on 2023-07-23 00:00:00+00:00
[2024-07-03T21:07:23.715+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=82) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-03T21:07:23.743+0000] {standard_task_runner.py:63} INFO - Started process 121 to run task
[2024-07-03T21:07:23.607+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'exchange_rate_dag', 'run_script', 'scheduled__2023-07-23T00:00:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpv9sh6r5r']
[2024-07-03T21:07:24.004+0000] {standard_task_runner.py:91} INFO - Job 16: Subtask run_script
[2024-07-03T21:07:25.667+0000] {task_command.py:426} INFO - Running <TaskInstance: exchange_rate_dag.run_script scheduled__2023-07-23T00:00:00+00:00 [running]> on host 539cd3e7956f
[2024-07-03T21:07:27.663+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='juan_ml' AIRFLOW_CTX_DAG_ID='exchange_rate_dag' AIRFLOW_CTX_TASK_ID='run_script' AIRFLOW_CTX_EXECUTION_DATE='2023-07-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-23T00:00:00+00:00'
[2024-07-03T21:07:27.668+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-03T21:07:27.671+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-03T21:07:27.673+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/my_dag.py", line 18, in main
    if not validate_credentials():
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/modules/validate_credentials.py", line 8, in validate_credentials
    "REDSHIFT_HOST": os.getenv('REDSHIFT_HOST').replace('http://', ''),
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'replace'
[2024-07-03T21:07:27.851+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=exchange_rate_dag, task_id=run_script, run_id=scheduled__2023-07-23T00:00:00+00:00, execution_date=20230723T000000, start_date=20240703T210722, end_date=20240703T210727
[2024-07-03T21:07:27.985+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 16 for task run_script ('NoneType' object has no attribute 'replace'; 121)
[2024-07-03T21:07:28.141+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-03T21:07:28.194+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
