[2024-07-03T21:35:09.998+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-03T21:35:10.053+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exchange_rate_dag.run_script scheduled__2024-02-04T00:00:00+00:00 [queued]>
[2024-07-03T21:35:10.072+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exchange_rate_dag.run_script scheduled__2024-02-04T00:00:00+00:00 [queued]>
[2024-07-03T21:35:10.073+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-03T21:35:10.102+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): run_script> on 2024-02-04 00:00:00+00:00
[2024-07-03T21:35:10.118+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=290) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-03T21:35:10.122+0000] {standard_task_runner.py:63} INFO - Started process 303 to run task
[2024-07-03T21:35:10.121+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'exchange_rate_dag', 'run_script', 'scheduled__2024-02-04T00:00:00+00:00', '--job-id', '86', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpsrj0lywf']
[2024-07-03T21:35:10.124+0000] {standard_task_runner.py:91} INFO - Job 86: Subtask run_script
[2024-07-03T21:35:10.214+0000] {task_command.py:426} INFO - Running <TaskInstance: exchange_rate_dag.run_script scheduled__2024-02-04T00:00:00+00:00 [running]> on host 539cd3e7956f
[2024-07-03T21:35:10.409+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='juan_ml' AIRFLOW_CTX_DAG_ID='exchange_rate_dag' AIRFLOW_CTX_TASK_ID='run_script' AIRFLOW_CTX_EXECUTION_DATE='2024-02-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-04T00:00:00+00:00'
[2024-07-03T21:35:10.413+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-03T21:35:10.415+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-03T21:35:10.416+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/my_dag.py", line 18, in main
    if not validate_credentials():
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/modules/validate_credentials.py", line 8, in validate_credentials
    "REDSHIFT_HOST": os.getenv('REDSHIFT_HOST').replace('http://', ''),
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'replace'
[2024-07-03T21:35:10.450+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=exchange_rate_dag, task_id=run_script, run_id=scheduled__2024-02-04T00:00:00+00:00, execution_date=20240204T000000, start_date=20240703T213510, end_date=20240703T213510
[2024-07-03T21:35:10.476+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 86 for task run_script ('NoneType' object has no attribute 'replace'; 303)
[2024-07-03T21:35:10.540+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-03T21:35:10.567+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-03T22:48:02.200+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-03T22:48:02.437+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exchange_rate_dag.run_script scheduled__2024-02-04T00:00:00+00:00 [queued]>
[2024-07-03T22:48:02.469+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exchange_rate_dag.run_script scheduled__2024-02-04T00:00:00+00:00 [queued]>
[2024-07-03T22:48:02.471+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-03T22:48:02.601+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): run_script> on 2024-02-04 00:00:00+00:00
[2024-07-03T22:48:02.662+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=72) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-03T22:48:02.666+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'exchange_rate_dag', 'run_script', 'scheduled__2024-02-04T00:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmp3a0r7lbi']
[2024-07-03T22:48:02.672+0000] {standard_task_runner.py:91} INFO - Job 12: Subtask run_script
[2024-07-03T22:48:02.668+0000] {standard_task_runner.py:63} INFO - Started process 109 to run task
[2024-07-03T22:48:03.179+0000] {task_command.py:426} INFO - Running <TaskInstance: exchange_rate_dag.run_script scheduled__2024-02-04T00:00:00+00:00 [running]> on host 0b7358cba041
[2024-07-03T22:48:04.030+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='juan_ml' AIRFLOW_CTX_DAG_ID='exchange_rate_dag' AIRFLOW_CTX_TASK_ID='run_script' AIRFLOW_CTX_EXECUTION_DATE='2024-02-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-04T00:00:00+00:00'
[2024-07-03T22:48:04.040+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-03T22:48:04.046+0000] {logging_mixin.py:188} INFO - All credentials are set properly.
[2024-07-03T22:48:04.049+0000] {logging_mixin.py:188} INFO - Error al crear la tabla en Redshift: invalid literal for int() with base 10: 'None'
[2024-07-03T22:48:05.028+0000] {logging_mixin.py:188} INFO - Error al realizar la solicitud a la API: 401 Client Error: Unauthorized for url: https://api.apilayer.com/exchangerates_data/latest?symbols=EUR,USD,CNY&base=ARS
[2024-07-03T22:48:05.042+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-03T22:48:05.050+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-03T22:48:05.163+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=exchange_rate_dag, task_id=run_script, run_id=scheduled__2024-02-04T00:00:00+00:00, execution_date=20240204T000000, start_date=20240703T224802, end_date=20240703T224805
[2024-07-03T22:48:05.301+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-03T22:48:05.392+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-03T22:48:05.408+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
