[2024-07-03T21:35:10.529+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-03T21:35:10.595+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exchange_rate_dag.run_script scheduled__2024-02-05T00:00:00+00:00 [queued]>
[2024-07-03T21:35:10.625+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exchange_rate_dag.run_script scheduled__2024-02-05T00:00:00+00:00 [queued]>
[2024-07-03T21:35:10.627+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-03T21:35:10.671+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): run_script> on 2024-02-05 00:00:00+00:00
[2024-07-03T21:35:10.691+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=292) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-03T21:35:10.695+0000] {standard_task_runner.py:63} INFO - Started process 304 to run task
[2024-07-03T21:35:10.697+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'exchange_rate_dag', 'run_script', 'scheduled__2024-02-05T00:00:00+00:00', '--job-id', '87', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmp65yt2mii']
[2024-07-03T21:35:10.700+0000] {standard_task_runner.py:91} INFO - Job 87: Subtask run_script
[2024-07-03T21:35:10.812+0000] {task_command.py:426} INFO - Running <TaskInstance: exchange_rate_dag.run_script scheduled__2024-02-05T00:00:00+00:00 [running]> on host 539cd3e7956f
[2024-07-03T21:35:10.957+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='juan_ml' AIRFLOW_CTX_DAG_ID='exchange_rate_dag' AIRFLOW_CTX_TASK_ID='run_script' AIRFLOW_CTX_EXECUTION_DATE='2024-02-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-05T00:00:00+00:00'
[2024-07-03T21:35:10.959+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-03T21:35:10.961+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-03T21:35:10.962+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/my_dag.py", line 18, in main
    if not validate_credentials():
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/modules/validate_credentials.py", line 8, in validate_credentials
    "REDSHIFT_HOST": os.getenv('REDSHIFT_HOST').replace('http://', ''),
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'replace'
[2024-07-03T21:35:10.985+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=exchange_rate_dag, task_id=run_script, run_id=scheduled__2024-02-05T00:00:00+00:00, execution_date=20240205T000000, start_date=20240703T213510, end_date=20240703T213510
[2024-07-03T21:35:11.006+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 87 for task run_script ('NoneType' object has no attribute 'replace'; 304)
[2024-07-03T21:35:11.033+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-03T21:35:11.055+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-03T21:35:11.059+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-03T22:48:04.665+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-03T22:48:04.764+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exchange_rate_dag.run_script scheduled__2024-02-05T00:00:00+00:00 [queued]>
[2024-07-03T22:48:04.821+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exchange_rate_dag.run_script scheduled__2024-02-05T00:00:00+00:00 [queued]>
[2024-07-03T22:48:04.825+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-03T22:48:04.943+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): run_script> on 2024-02-05 00:00:00+00:00
[2024-07-03T22:48:04.982+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=75) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-03T22:48:04.991+0000] {standard_task_runner.py:63} INFO - Started process 113 to run task
[2024-07-03T22:48:04.999+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'exchange_rate_dag', 'run_script', 'scheduled__2024-02-05T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpgv8j1rwi']
[2024-07-03T22:48:05.012+0000] {standard_task_runner.py:91} INFO - Job 13: Subtask run_script
[2024-07-03T22:48:05.334+0000] {task_command.py:426} INFO - Running <TaskInstance: exchange_rate_dag.run_script scheduled__2024-02-05T00:00:00+00:00 [running]> on host 0b7358cba041
[2024-07-03T22:48:05.786+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='juan_ml' AIRFLOW_CTX_DAG_ID='exchange_rate_dag' AIRFLOW_CTX_TASK_ID='run_script' AIRFLOW_CTX_EXECUTION_DATE='2024-02-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-05T00:00:00+00:00'
[2024-07-03T22:48:05.810+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-03T22:48:05.823+0000] {logging_mixin.py:188} INFO - All credentials are set properly.
[2024-07-03T22:48:05.827+0000] {logging_mixin.py:188} INFO - Error al crear la tabla en Redshift: invalid literal for int() with base 10: 'None'
[2024-07-03T22:48:06.898+0000] {logging_mixin.py:188} INFO - Error al realizar la solicitud a la API: 401 Client Error: Unauthorized for url: https://api.apilayer.com/exchangerates_data/latest?symbols=EUR,USD,CNY&base=ARS
[2024-07-03T22:48:06.905+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-03T22:48:06.917+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-03T22:48:06.963+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=exchange_rate_dag, task_id=run_script, run_id=scheduled__2024-02-05T00:00:00+00:00, execution_date=20240205T000000, start_date=20240703T224804, end_date=20240703T224806
[2024-07-03T22:48:07.050+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-03T22:48:07.126+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-03T22:48:07.160+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
