[2024-07-03T23:26:25.387+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-03T23:26:25.792+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exchange_rate_dag.run_script scheduled__2024-05-20T00:00:00+00:00 [queued]>
[2024-07-03T23:26:25.929+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exchange_rate_dag.run_script scheduled__2024-05-20T00:00:00+00:00 [queued]>
[2024-07-03T23:26:25.931+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-03T23:26:26.108+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): run_script> on 2024-05-20 00:00:00+00:00
[2024-07-03T23:26:26.152+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=820) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-03T23:26:26.169+0000] {standard_task_runner.py:63} INFO - Started process 835 to run task
[2024-07-03T23:26:26.168+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'exchange_rate_dag', 'run_script', 'scheduled__2024-05-20T00:00:00+00:00', '--job-id', '116', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmphmqar3mt']
[2024-07-03T23:26:26.192+0000] {standard_task_runner.py:91} INFO - Job 116: Subtask run_script
[2024-07-03T23:26:26.499+0000] {task_command.py:426} INFO - Running <TaskInstance: exchange_rate_dag.run_script scheduled__2024-05-20T00:00:00+00:00 [running]> on host 0b7358cba041
[2024-07-03T23:26:27.474+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='juan_ml' AIRFLOW_CTX_DAG_ID='exchange_rate_dag' AIRFLOW_CTX_TASK_ID='run_script' AIRFLOW_CTX_EXECUTION_DATE='2024-05-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-20T00:00:00+00:00'
[2024-07-03T23:26:27.491+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-03T23:26:27.504+0000] {logging_mixin.py:188} INFO - All credentials are set properly.
[2024-07-03T23:26:27.558+0000] {logging_mixin.py:188} INFO - Error al crear la tabla en Redshift: invalid literal for int() with base 10: 'None'
[2024-07-03T23:26:39.456+0000] {logging_mixin.py:188} INFO - Error al realizar la solicitud a la API: HTTPSConnectionPool(host='api.apilayer.com', port=443): Max retries exceeded with url: /exchangerates_data/latest?symbols=EUR,USD,CNY&base=ARS (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f7c8e449a30>: Failed to resolve 'api.apilayer.com' ([Errno -3] Temporary failure in name resolution)"))
[2024-07-03T23:26:40.763+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-03T23:27:19.507+0000] {local_task_job_runner.py:240} INFO - Task exited with return code -9
[2024-07-03T23:27:19.639+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-03T23:27:19.662+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
