[2024-07-03T21:08:00.239+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-03T21:08:00.269+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exchange_rate_dag.run_script scheduled__2023-07-01T00:00:00+00:00 [queued]>
[2024-07-03T21:08:00.281+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exchange_rate_dag.run_script scheduled__2023-07-01T00:00:00+00:00 [queued]>
[2024-07-03T21:08:01.519+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-03T21:08:04.321+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): run_script> on 2023-07-01 00:00:00+00:00
[2024-07-03T21:08:04.338+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=104) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-03T21:08:04.342+0000] {standard_task_runner.py:63} INFO - Started process 144 to run task
[2024-07-03T21:08:04.341+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'exchange_rate_dag', 'run_script', 'scheduled__2023-07-01T00:00:00+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmp7qa6phpc']
[2024-07-03T21:08:04.343+0000] {standard_task_runner.py:91} INFO - Job 26: Subtask run_script
[2024-07-03T21:08:05.989+0000] {task_command.py:426} INFO - Running <TaskInstance: exchange_rate_dag.run_script scheduled__2023-07-01T00:00:00+00:00 [running]> on host 539cd3e7956f
[2024-07-03T21:08:09.348+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='juan_ml' AIRFLOW_CTX_DAG_ID='exchange_rate_dag' AIRFLOW_CTX_TASK_ID='run_script' AIRFLOW_CTX_EXECUTION_DATE='2023-07-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-01T00:00:00+00:00'
[2024-07-03T21:08:09.351+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-03T21:08:09.352+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-03T21:08:09.353+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/my_dag.py", line 18, in main
    if not validate_credentials():
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/modules/validate_credentials.py", line 8, in validate_credentials
    "REDSHIFT_HOST": os.getenv('REDSHIFT_HOST').replace('http://', ''),
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'replace'
[2024-07-03T21:08:09.381+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=exchange_rate_dag, task_id=run_script, run_id=scheduled__2023-07-01T00:00:00+00:00, execution_date=20230701T000000, start_date=20240703T210800, end_date=20240703T210809
[2024-07-03T21:08:10.208+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 26 for task run_script ('NoneType' object has no attribute 'replace'; 144)
[2024-07-03T21:08:10.794+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-03T21:08:10.820+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-03T21:08:11.266+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
