[2024-07-03T21:36:43.605+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: exchange_rate_dag.run_script scheduled__2024-01-29T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
[2024-07-03T23:02:36.914+0000] {scheduler_job_runner.py:1737} ERROR - Detected zombie job: {'full_filepath': '/opt/airflow/dags/my_dag.py', 'processor_subdir': '/opt/airflow/dags', 'msg': "{'DAG Id': 'exchange_rate_dag', 'Task Id': 'run_script', 'Run Id': 'scheduled__2024-01-29T00:00:00+00:00', 'Hostname': '0b7358cba041', 'External Executor Id': '934ab215-22ba-4e99-ac9b-9fa1d98709f0'}", 'simple_task_instance': <airflow.models.taskinstance.SimpleTaskInstance object at 0x7f48e9abf8c0>, 'is_failure_callback': True} (See https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/tasks.html#zombie-undead-tasks)
[2024-07-03T23:02:49.346+0000] {scheduler_job_runner.py:1737} ERROR - Detected zombie job: {'full_filepath': '/opt/airflow/dags/my_dag.py', 'processor_subdir': '/opt/airflow/dags', 'msg': "{'DAG Id': 'exchange_rate_dag', 'Task Id': 'run_script', 'Run Id': 'scheduled__2024-01-29T00:00:00+00:00', 'Hostname': '0b7358cba041', 'External Executor Id': '934ab215-22ba-4e99-ac9b-9fa1d98709f0'}", 'simple_task_instance': <airflow.models.taskinstance.SimpleTaskInstance object at 0x7f48e9a0c050>, 'is_failure_callback': True} (See https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/tasks.html#zombie-undead-tasks)
