[2024-07-03T23:14:49.064+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-03T23:14:50.055+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exchange_rate_dag.run_script scheduled__2024-03-27T00:00:00+00:00 [queued]>
[2024-07-03T23:14:50.168+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exchange_rate_dag.run_script scheduled__2024-03-27T00:00:00+00:00 [queued]>
[2024-07-03T23:14:50.259+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-03T23:14:50.967+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): run_script> on 2024-03-27 00:00:00+00:00
[2024-07-03T23:14:51.002+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=452) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-03T23:14:51.006+0000] {standard_task_runner.py:63} INFO - Started process 489 to run task
[2024-07-03T23:14:51.006+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'exchange_rate_dag', 'run_script', 'scheduled__2024-03-27T00:00:00+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmp2w5nv4dd']
[2024-07-03T23:14:51.009+0000] {standard_task_runner.py:91} INFO - Job 46: Subtask run_script
[2024-07-03T23:14:51.579+0000] {task_command.py:426} INFO - Running <TaskInstance: exchange_rate_dag.run_script scheduled__2024-03-27T00:00:00+00:00 [running]> on host 0b7358cba041
[2024-07-03T23:14:52.984+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='juan_ml' AIRFLOW_CTX_DAG_ID='exchange_rate_dag' AIRFLOW_CTX_TASK_ID='run_script' AIRFLOW_CTX_EXECUTION_DATE='2024-03-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-27T00:00:00+00:00'
[2024-07-03T23:14:52.987+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-03T23:14:52.990+0000] {logging_mixin.py:188} INFO - All credentials are set properly.
[2024-07-03T23:14:52.992+0000] {logging_mixin.py:188} INFO - Error al crear la tabla en Redshift: invalid literal for int() with base 10: 'None'
[2024-07-03T23:15:03.229+0000] {logging_mixin.py:188} INFO - Error al realizar la solicitud a la API: HTTPSConnectionPool(host='api.apilayer.com', port=443): Max retries exceeded with url: /exchangerates_data/latest?symbols=EUR,USD,CNY&base=ARS (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f7c8e315910>: Failed to resolve 'api.apilayer.com' ([Errno -3] Temporary failure in name resolution)"))
[2024-07-03T23:15:03.283+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-03T23:15:03.302+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-03T23:15:26.830+0000] {local_task_job_runner.py:240} INFO - Task exited with return code -9
[2024-07-03T23:15:27.029+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-03T23:15:27.449+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
