[2024-07-03T23:14:49.066+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-03T23:14:49.571+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exchange_rate_dag.run_script scheduled__2024-04-02T00:00:00+00:00 [queued]>
[2024-07-03T23:14:49.613+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exchange_rate_dag.run_script scheduled__2024-04-02T00:00:00+00:00 [queued]>
[2024-07-03T23:14:49.808+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-03T23:14:50.047+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): run_script> on 2024-04-02 00:00:00+00:00
[2024-07-03T23:14:50.119+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=462) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-03T23:14:50.131+0000] {standard_task_runner.py:63} INFO - Started process 487 to run task
[2024-07-03T23:14:50.150+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'exchange_rate_dag', 'run_script', 'scheduled__2024-04-02T00:00:00+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmp5rwdemg2']
[2024-07-03T23:14:50.170+0000] {standard_task_runner.py:91} INFO - Job 47: Subtask run_script
[2024-07-03T23:14:50.840+0000] {task_command.py:426} INFO - Running <TaskInstance: exchange_rate_dag.run_script scheduled__2024-04-02T00:00:00+00:00 [running]> on host 0b7358cba041
[2024-07-03T23:14:52.161+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='juan_ml' AIRFLOW_CTX_DAG_ID='exchange_rate_dag' AIRFLOW_CTX_TASK_ID='run_script' AIRFLOW_CTX_EXECUTION_DATE='2024-04-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-02T00:00:00+00:00'
[2024-07-03T23:14:52.167+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-03T23:14:52.169+0000] {logging_mixin.py:188} INFO - All credentials are set properly.
[2024-07-03T23:14:52.171+0000] {logging_mixin.py:188} INFO - Error al crear la tabla en Redshift: invalid literal for int() with base 10: 'None'
[2024-07-03T23:15:02.581+0000] {logging_mixin.py:188} INFO - Error al realizar la solicitud a la API: HTTPSConnectionPool(host='api.apilayer.com', port=443): Max retries exceeded with url: /exchangerates_data/latest?symbols=EUR,USD,CNY&base=ARS (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f7c8e1cbc20>: Failed to resolve 'api.apilayer.com' ([Errno -3] Temporary failure in name resolution)"))
[2024-07-03T23:15:03.160+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-03T23:15:03.281+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-03T23:15:26.425+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=exchange_rate_dag, task_id=run_script, run_id=scheduled__2024-04-02T00:00:00+00:00, execution_date=20240402T000000, start_date=20240703T231449, end_date=20240703T231526
[2024-07-03T23:15:27.810+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-03T23:15:28.071+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-03T23:15:28.221+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
