[2024-07-03T21:36:51.741+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-03T21:36:51.820+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exchange_rate_dag.run_script scheduled__2024-02-06T00:00:00+00:00 [queued]>
[2024-07-03T21:36:51.856+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exchange_rate_dag.run_script scheduled__2024-02-06T00:00:00+00:00 [queued]>
[2024-07-03T21:36:51.861+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-03T21:36:51.919+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): run_script> on 2024-02-06 00:00:00+00:00
[2024-07-03T21:36:51.944+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=344) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-03T21:36:51.951+0000] {standard_task_runner.py:63} INFO - Started process 346 to run task
[2024-07-03T21:36:51.948+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'exchange_rate_dag', 'run_script', 'scheduled__2024-02-06T00:00:00+00:00', '--job-id', '89', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpgjokqwan']
[2024-07-03T21:36:51.957+0000] {standard_task_runner.py:91} INFO - Job 89: Subtask run_script
[2024-07-03T21:36:52.177+0000] {task_command.py:426} INFO - Running <TaskInstance: exchange_rate_dag.run_script scheduled__2024-02-06T00:00:00+00:00 [running]> on host 539cd3e7956f
[2024-07-03T21:36:52.520+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='juan_ml' AIRFLOW_CTX_DAG_ID='exchange_rate_dag' AIRFLOW_CTX_TASK_ID='run_script' AIRFLOW_CTX_EXECUTION_DATE='2024-02-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-06T00:00:00+00:00'
[2024-07-03T21:36:52.524+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-03T21:36:52.528+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-03T21:36:52.529+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/my_dag.py", line 18, in main
    if not validate_credentials():
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/modules/validate_credentials.py", line 8, in validate_credentials
    "REDSHIFT_HOST": os.getenv('REDSHIFT_HOST').replace('http://', ''),
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'replace'
[2024-07-03T21:36:52.592+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=exchange_rate_dag, task_id=run_script, run_id=scheduled__2024-02-06T00:00:00+00:00, execution_date=20240206T000000, start_date=20240703T213651, end_date=20240703T213652
[2024-07-03T21:36:52.627+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 89 for task run_script ('NoneType' object has no attribute 'replace'; 346)
[2024-07-03T21:36:52.669+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-03T21:36:52.732+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-03T21:36:52.738+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-03T22:48:00.257+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-03T22:48:00.324+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exchange_rate_dag.run_script scheduled__2024-02-06T00:00:00+00:00 [queued]>
[2024-07-03T22:48:00.346+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exchange_rate_dag.run_script scheduled__2024-02-06T00:00:00+00:00 [queued]>
[2024-07-03T22:48:00.348+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-03T22:48:00.410+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): run_script> on 2024-02-06 00:00:00+00:00
[2024-07-03T22:48:00.448+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=77) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-03T22:48:00.459+0000] {standard_task_runner.py:63} INFO - Started process 106 to run task
[2024-07-03T22:48:00.456+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'exchange_rate_dag', 'run_script', 'scheduled__2024-02-06T00:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpcmh5alhn']
[2024-07-03T22:48:00.465+0000] {standard_task_runner.py:91} INFO - Job 10: Subtask run_script
[2024-07-03T22:48:00.661+0000] {task_command.py:426} INFO - Running <TaskInstance: exchange_rate_dag.run_script scheduled__2024-02-06T00:00:00+00:00 [running]> on host 0b7358cba041
[2024-07-03T22:48:01.095+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='juan_ml' AIRFLOW_CTX_DAG_ID='exchange_rate_dag' AIRFLOW_CTX_TASK_ID='run_script' AIRFLOW_CTX_EXECUTION_DATE='2024-02-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-06T00:00:00+00:00'
[2024-07-03T22:48:01.099+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-03T22:48:01.106+0000] {logging_mixin.py:188} INFO - All credentials are set properly.
[2024-07-03T22:48:01.112+0000] {logging_mixin.py:188} INFO - Error al crear la tabla en Redshift: invalid literal for int() with base 10: 'None'
[2024-07-03T22:48:01.910+0000] {logging_mixin.py:188} INFO - Error al realizar la solicitud a la API: 401 Client Error: Unauthorized for url: https://api.apilayer.com/exchangerates_data/latest?symbols=EUR,USD,CNY&base=ARS
[2024-07-03T22:48:01.925+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-03T22:48:01.939+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-03T22:48:02.007+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=exchange_rate_dag, task_id=run_script, run_id=scheduled__2024-02-06T00:00:00+00:00, execution_date=20240206T000000, start_date=20240703T224800, end_date=20240703T224802
[2024-07-03T22:48:02.156+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-03T22:48:02.331+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-03T22:48:02.380+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-04T01:35:15.135+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-04T01:35:15.217+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exchange_rate_dag.run_script scheduled__2024-02-06T00:00:00+00:00 [queued]>
[2024-07-04T01:35:15.236+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exchange_rate_dag.run_script scheduled__2024-02-06T00:00:00+00:00 [queued]>
[2024-07-04T01:35:15.237+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-04T01:35:15.375+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): run_script> on 2024-02-06 00:00:00+00:00
[2024-07-04T01:35:15.476+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=281) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-04T01:35:15.481+0000] {standard_task_runner.py:63} INFO - Started process 283 to run task
[2024-07-04T01:35:15.483+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'exchange_rate_dag', 'run_script', 'scheduled__2024-02-06T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmptlgg6e0v']
[2024-07-04T01:35:15.486+0000] {standard_task_runner.py:91} INFO - Job 7: Subtask run_script
[2024-07-04T01:35:15.767+0000] {task_command.py:426} INFO - Running <TaskInstance: exchange_rate_dag.run_script scheduled__2024-02-06T00:00:00+00:00 [running]> on host e26a552f405a
[2024-07-04T01:35:16.210+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='juan_ml' AIRFLOW_CTX_DAG_ID='exchange_rate_dag' AIRFLOW_CTX_TASK_ID='run_script' AIRFLOW_CTX_EXECUTION_DATE='2024-02-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-06T00:00:00+00:00'
[2024-07-04T01:35:16.212+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-04T01:35:16.214+0000] {logging_mixin.py:188} INFO - All credentials are set properly.
[2024-07-04T01:35:16.215+0000] {logging_mixin.py:188} INFO - Error al crear la tabla en Redshift: invalid literal for int() with base 10: 'None'
[2024-07-04T01:35:17.517+0000] {logging_mixin.py:188} INFO - Error al realizar la solicitud a la API: 401 Client Error: Unauthorized for url: https://api.apilayer.com/exchangerates_data/latest?symbols=EUR,USD,CNY&base=ARS
[2024-07-04T01:35:17.521+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-04T01:35:17.523+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-04T01:35:17.542+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=exchange_rate_dag, task_id=run_script, run_id=scheduled__2024-02-06T00:00:00+00:00, execution_date=20240206T000000, start_date=20240704T013515, end_date=20240704T013517
[2024-07-04T01:35:17.627+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-04T01:35:17.657+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-04T01:35:17.661+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
